name: Tagged release
run-name: ${{ github.actor }} has started a build to release
on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
env:
  ZIPFILE_NAME: OldEbonheartApartment
  README_NAME: Old Ebonheart Apartment Readme
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: ls -la ${{ github.workspace }}

      - name: Package mod
        run: |
          cd '${{ github.workspace }}/Data Files/' && zip -r ${{ github.workspace }}/${{ env.ZIPFILE_NAME }}.zip .
          cd '${{ github.workspace }}/Data Files/' && zip -x "${{ env.README_NAME }}.txt" -r ${{ github.workspace }}/${{ env.ZIPFILE_NAME }}-no-readme.zip .

      - name: Get tag
        id: tag
        run: |
          TAG=$(git describe --exact-match --tags)
          echo "$TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Verify tag
        run: echo ${{ steps.tag.outputs.tag }}

      - name: Create Release and Upload
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.ZIPFILE_NAME }}.zip
            ${{ env.ZIPFILE_NAME }}-no-readme.zip
          tag_name: ${{ steps.tag.outputs.tag }}
